# bump_build.cmake — 빌드 번호 관리 (major.minor.build의 build 부분).
#
# TXT(저장소 루트 build_number.txt) = 현재 빌드 번호. x64/x86 빌드 트리가 공유한다.
# STAMP(각 빌드 트리의 build_stamp.txt) = 이 트리가 마지막으로 사용한 번호.
#
# 규칙(같은 라운드의 x64/x86 쌍이 같은 번호를 갖도록):
#   * STAMP == TXT 번호  → 이 아키텍처는 이 번호로 이미 빌드했음 = 새 빌드 라운드
#                          → 번호 +1 (TXT 갱신)
#   * STAMP <  TXT 번호  → 다른 아키텍처가 이미 올린 라운드에 합류 → 번호 그대로
# 이후 STAMP를 현재 번호로 찍고 HDR(BuildNum.h)을 생성한다.
# STAMP 미지정(구성 시점) 시에는 번호 반영만 하고 소비하지 않는다.

file(READ ${TXT} _n)
string(STRIP "${_n}" _n)
if(NOT _n MATCHES "^[0-9]+$")
  set(_n 0)
endif()

if(DEFINED STAMP)
  set(_s -1)
  if(EXISTS ${STAMP})
    file(READ ${STAMP} _s)
    string(STRIP "${_s}" _s)
    if(NOT _s MATCHES "^[0-9]+$")
      set(_s -1)
    endif()
  endif()
  if(_s EQUAL _n)
    math(EXPR _n "${_n} + 1")
    file(WRITE ${TXT} "${_n}")
  endif()
  file(WRITE ${STAMP} "${_n}")
endif()

file(WRITE ${HDR} "// Generated by cmake/bump_build.cmake - do not edit, not committed.
#ifndef EG_BUILDNUM_H
#define EG_BUILDNUM_H
#define EG_BUILD_NUM ${_n}
// full version string \"major.minor.build\" - EG_VER_MAJOR/MINOR come from
// compile definitions (CMakeLists PROJECT_VERSION).
#define EG_VER_STR2_(x) #x
#define EG_VER_STR_(x) EG_VER_STR2_(x)
#define EG_VERSION_STR EG_VER_STR_(EG_VER_MAJOR) \".\" EG_VER_STR_(EG_VER_MINOR) \".\" EG_VER_STR_(EG_BUILD_NUM)
#endif
")
